SerializedClasses:
    - gss.bot.models.Server
    - gss.ircbot.models.queues.IrcMessageQueue
    - gss.ircbot.models.queues.UserActionQueue
    - gss.bot.models.BotProfile
    - gss.bot.models.User
    - gss.bot.models.Channel
    - gss.bot.models.UserAuthentication
    - gss.bot.models.KeyStore
    - gss.ircbot.models.UserAutoAuthentication
    # - a.Class
queues:
    # a.queue(: an.event)
    gss.ircbot.models.queues.IrcMessageQueue:
    gss.ircbot.models.queues.UserActionQueue:
events:
    # an.event.trigger<.class>:
        # - an.event
